[package]
name = "core-logic"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
flume = "0.10.14"
lazy_static = "1.4.0"
regex = "1.7.0"
log = "0.4.0"
bevy_ecs = "0.9.0"
itertools = "0.10.5"